populations = { lambda x: x[0].isdigit(): 'North America',
                lambda x: x.startswith('B'): 'China',
                lambda x: x.startswith('C'): 'Africa',
                lambda x: x.startswith('E'): 'Ethiopa',
                lambda x: x.startswith('F'): 'France',
                lambda x: x.startswith('G'): 'Georgia',
                lambda x: x.startswith('H'): 'Haiti',
                lambda x: x.startswith('I'): 'Ithaca NY',
                lambda x: x.startswith('K'): 'Kenya',
                lambda x: x.startswith('N'): 'Netherlands',
                lambda x: x.startswith('RAL'): 'Raleigh North Carolina',
                lambda x: x.startswith('RC'): 'Rwanda',
                lambda x: x.startswith('RA'): 'Rwanda',
                lambda x: x.startswith('S'): 'South Africa',
                lambda x: x.startswith('T'): 'Australia',
                lambda x: x.startswith('W'): 'California',
                lambda x: x.startswith('ZH') : 'Zimbabwe',
                lambda x: x.startswith('ZK'): 'Zimbabwe',
                lambda x: x.startswith('ZS'): 'Zimbabwe',
                lambda x: x.startswith('ZW'): 'Zimbabwe',
                lambda x: x.startswith('ZI') : 'Zambia',
                lambda x: x.startswith('ZL'): 'Zambia',
                lambda x: x.startswith('ZO'): 'Zambia',
                lambda x: x.startswith('b'): 'China',
                lambda x: x.startswith('t'): 'lower_t',
                lambda x: x.startswith('w'): 'lower_w',
}

